### PR TITLE
enhancement #43: Bing CustomMapStyle support

### PR DESCRIPTION
**Pull request by ChristopherSenn**
I added Support for Bing CustomMapStyle.
In my local tests everything worked fine.

### CODE REVIEW

**Comment by thor-schueler** [comment]
This will of course work fine with Bing. But not so much with google. Would it be better to abstract this and create a Bing specific implementation, mapping the bing attributes onto the abstract attributes and then do the same with Google (and any future providers)? Or are we just saying this attribute CustomMapStyle is supported on Bing only? I guess we can always implement a conversion at a later point in Google-conversions.ts. Thoughts?

**Comment by ChristopherSenn** [comment]
Oh yeah, you are absolutely right, I didn't think about Google at all.
I think it would be better to try to abstract the interface and create Bing and Google implementations.
However, I don't really have an idea on how to do that right now.
Would I just implement all the features of Bing and Google combined in the ICustomMapStyle interface and then map all the attributes that are supported by Bing to the Bing implementation and do the same for Google?

**Comment by thor-schueler** [comment]
Well, the best way would be to assess what both Google and Bing can support and what is exclusive to either and adjust the interface accordingly. Perhaps have the common supported attributes as properties in the interface and the exclusive ones in a separate property? Then, in bing-conversions.ts and google-converstions.ts we'd implement the mapping onto the actual Bing/Google structures and properties. This i, actually, what you have already done for bing. So I'll just push this change and we can work on the google aspects later...

**Comment by ChristopherSenn** [comment]
I implemented an interface for Google Maps this weekend, however I don't have the time right now to compare Google and Bing to make a general interface for both of them. (On first glance there seemed to be quite some differences)
If you want I can create a Pull request for that.
Right now that would mean we would have a customMapStyleBing and a customMapStyleGoogle attribute in the IMapOptions interface.

**Comment by thor-schueler** [comment]
Yes let’s. We can reconcile it at a later time.
Thanks!

**Pull request merged**
