### PR TITLE
Using ng packagr

### PR DESCRIPTION
**Pull request by METACEO**

### CODE REVIEW

**Comment by METACEO** [comment]
@thor-schueler - this PR is opened and, once merged, will require you to publish differently than before. Please try the following:
1. At the root of the project, run `npm run package`
2. Enter the `dist` folder.
3. [Increase the version of the package](https://docs.npmjs.com/cli/version) (I think we talked about `6.0.0` to align with Angular?) You should be able to run `npm version 6.0.0` to update the `package.json` file.
4. Run `npm publish`

**Comment by METACEO** [comment]
#68

**Comment by thor-schueler** [comment]
@METACEO If you are in tomorrow, let's work through it together...

**Comment by METACEO** [comment]
@thor-schueler - I'll be trying to!

**Comment by jmsunseri** [comment]
when should we be expecting this?

**Comment by jmsunseri** [comment]
Any update on this?

**Comment by thor-schueler** [comment]
@jmsunseri We've just merged and published. We went to version 6.0.0 to get in sync with the ng versioning...

**Comment by jmsunseri** [comment]
I updated my app and things are working. Thanks for getting this updated!

**Pull request merged**
